const wishlistGames = [
  {
    appId: 2623190,
    priority: 0,
    dateAdded: 1711234567,
    name: "The Elder Scrolls IV: Oblivion Remastered",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2623190/header.jpg",
    description: "Explora Cyrodiil como nunca con unos gráficos impresionantes y una jugabilidad mejorada en The Elder Scrolls IV: Oblivion™ Remastered.",
    price: "54.99€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 29, description: "Steam Trading Cards" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "1", description: "Action" },
      { id: "56", description: "RPG" },
    ],
    releaseDate: "Coming Soon",
    comingSoon: true,
    developers: ["Bethesda Game Studios"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 3159330,
    priority: 1,
    dateAdded: 1712345678,
    name: "Assassin's Creed Shadows",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3159330/header.jpg",
    description: "Sumérgete en una épica historia de acción y aventura ambientada en el Japón feudal.",
    price: "69.99€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 29, description: "Steam Trading Cards" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "1", description: "Action" },
      { id: "2", description: "Adventure" },
    ],
    releaseDate: "Coming Soon",
    comingSoon: true,
    developers: ["Ubisoft"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 1729740,
    priority: 2,
    dateAdded: 1713456789,
    name: "Luto",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1729740/header.jpg",
    description: "Luto es una experiencia de terror psicológico en la que asumes el papel de alguien incapaz de abandonar su hogar.",
    price: "19.99€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "Coming Soon",
    comingSoon: true,
    developers: ["Broken Bird Games"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 2479740,
    priority: 3,
    dateAdded: 1714567890,
    name: "Pieces of Me",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2479740/header.jpg",
    description: "Un drama de suspenso psicológico en el género de walking simulator, spin-off del juego September 7th.",
    price: "8.79€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "Coming Soon",
    comingSoon: true,
    developers: ["Dystortion"],
    platforms: { windows: true, mac: true, linux: false },
  },
  {
    appId: 1766740,
    priority: 4,
    dateAdded: 1715678901,
    name: "Choo-Choo Charles",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1766740/header.jpg",
    description: "Juego de terror y supervivencia con un tren demoníaco.",
    price: "19.50€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 29, description: "Steam Trading Cards" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "1", description: "Action" },
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "9 Dec, 2022",
    comingSoon: false,
    developers: ["Two Star Games"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 1671340,
    priority: 5,
    dateAdded: 1716789012,
    name: "Fears To Fathom",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1671340/header.jpg",
    description: "Serie episódica de juegos de terror psicológico.",
    price: "Gratuito",
    originalPrice: null,
    discount: 0,
    isFree: true,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "2 Oct, 2021",
    comingSoon: false,
    developers: ["Rayll"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 3168370,
    priority: 6,
    dateAdded: 1717890123,
    name: "Bring Me...",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3168370/header.jpg",
    description: "Juega como una joven que ha estado cuidando de su padre enfermo. Observa tu entorno en busca de anomalías.",
    price: "3.99€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "Coming Soon",
    comingSoon: true,
    developers: ["Emy Live"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 3205080,
    priority: 7,
    dateAdded: 1718901234,
    name: "Bad Parenting 1: Mr. Red Face",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3205080/header.jpg",
    description: "Mr. Red Face, a fictional character created by adults to teach their children, suddenly becomes real.",
    price: "1.99€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "1", description: "Action" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "2025",
    comingSoon: false,
    developers: ["Horror Dev"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 2314720,
    priority: 8,
    dateAdded: 1719012345,
    name: "[Chilla's Art] Parasocial | パラソーシャル",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2314720/header.jpg",
    description: "Juego de terror psicológico donde eres una streamer.",
    price: "7.79€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "17 May, 2024",
    comingSoon: false,
    developers: ["Chilla's Art"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 2989950,
    priority: 9,
    dateAdded: 1720123456,
    name: "The Bathhouse | 地獄銭湯 Restored Edition",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2989950/header.jpg",
    description: "Juego de terror psicológico ambientado en un baño público.",
    price: "7.79€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "14 Jun, 2024",
    comingSoon: false,
    developers: ["Chilla's Art"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 2593900,
    priority: 10,
    dateAdded: 1721234567,
    name: "[Chilla's Art] The Kidnap | 誘拐事件",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2593900/header.jpg",
    description: "Juego de terror psicológico basado en un secuestro.",
    price: "9.75€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "10 May, 2024",
    comingSoon: false,
    developers: ["Chilla's Art"],
    platforms: { windows: true, mac: false, linux: false },
  },
  {
    appId: 2200190,
    priority: 11,
    dateAdded: 1722345678,
    name: "[Chilla's Art] The Karaoke | ヒトカラ🎤",
    type: "game",
    headerImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2200190/header.jpg",
    description: "Juego de terror psicológico ambientado en un karaoke.",
    price: "5.89€",
    originalPrice: null,
    discount: 0,
    isFree: false,
    categories: [
      { id: 2, description: "Single-player" },
      { id: 22, description: "Steam Achievements" },
      { id: 23, description: "Steam Cloud" },
    ],
    genres: [
      { id: "2", description: "Adventure" },
      { id: "73", description: "Indie" },
    ],
    releaseDate: "8 Sep, 2023",
    comingSoon: false,
    developers: ["Chilla's Art"],
    platforms: { windows: true, mac: false, linux: false },
  },
]

const wishlistLastUpdate = "2026-07-07T00:00:00Z"
